### ISSUE TITLE
Custom database

### ISSUE THREAD

**Issue by saroltm** [sirius-ms/sirius#105]
I have tried to create custom database in SIRIUS 5.6.3, just by clicking on database and adding the SMILES it doesn't create it. I believe there is a problem that I am not able to create a name for it, so I cannot save it. ( I can paste the SMILES but then I am not able to do anything further.)
Am I overlooking something, and new costum database can be created somehow else?
Thank you in advance

**Comment by EvilMetabolomics** [comment]
Hello Sirius developer team!
I have the same issue and would be interested in the solution. Thank you!

**Comment by mfleisch** [comment]
Hey,
there is an bug with white spaces in custom dbs in SIRIUS 5 that will not be fixed anymore. Not sure if this is causing this issue. 

However custom dbs have been improved a lot in SIRIUS 6. Can you please try SIRIUS 6.0.4 upwards and see if you still have problems.

Please also have a look on our updated documentation to get started:
GUI: https://v6.docs.sirius-ms.io/gui/#custom-database-import
CLI: https://v6.docs.sirius-ms.io/cli-standalone/#custom-database-tool

Closing this, feel free to reopen in case you still have problems.
