### ISSUE TITLE
Web-based tools not accessible

### ISSUE THREAD

**Issue by gfschnei** [sirius-ms/sirius#118]
Since Tuesday 5/2 I have been unable to access any of the web-based computational tools using the GUI. 
I was using v. 5.6.3 winx64 when I first encountered the issue. Have subsequently tried using 5.6.4 and 5.7.0 and the problem remains. 
The connection check indicates that all services are connected and available, but the computation request either fails immediately or hangs at 0% progress.
![sirius_bug](https://user-images.githubusercontent.com/54075577/236340967-34db1156-1682-4fc9-8bf6-5281391ce065.png)

**Comment by mfleisch** [comment]
Does this issue still persist?

**Comment by mfleisch** [comment]
Closing because this was likely a temporary issue and the ticket is stale.
