### ISSUE TITLE
Why are some structures missing in the "compound_identifications.tsv" table compared to the "formula_identifications.tsv" table?

### ISSUE THREAD

**Issue by peijiying** [sirius-ms/sirius#122]
In the "formula_identifications.tsv" table, molecular formulas are predicted for a total of 5049 compounds. However, only 3319 of these compounds have corresponding structures listed in the "compound_identifications.tsv" table.

For the remaining 1730 compounds that lack structures in the "compound_identifications.tsv" table, you can still access structural information for some of them through the Sirius GUI interface. Additionally, there is a possibility that structures for some of these compounds are available in the "structure_candidates.tsv" file, which can be found within the respective compound level's folder. So what is wrong? It is confused. Thank you for the answer.

**Comment by mfleisch** [comment]
Hey, can you please provide some data provide a description how to produce the results.
