### ISSUE TITLE
Negative mode spectra not loading

### ISSUE THREAD

**Issue by pmathew1** [sirius-ms/sirius#124]
I have converted negative mode MS/MS data acquired on a bruker MaXis plus to .mzXml, using the GNPS vendor conversion folder system. When I try to import these negative mode chromatograms, no spectra is imported/no compounds appear in the pane.
I tried with previously acquired negative-mode data for this project, which worked fine.
I am using v 5.6.3
Is this a Sirius settings issue? Something potentially with the raw data or conversion (the positive mode runs from this batch work fine), or potentially a software version issue? 
Thanks,
Paul

**Comment by mfleisch** [comment]
there have been some fixes regarding importing negative mode data recently. Please upgrade to the latest version.
If the issue still persists please provide example data that is causing the issue.
