### ISSUE TITLE
Not all compounds in summaries

### ISSUE THREAD

**Issue by MilouArts** [sirius-ms/sirius#130]
I used sirius to predict molecular formulas on 27129 features (till 850 da, 27856 features total)
Zodiac doesn't run because it takes too much memory and SIRIUS crashes (but that is not the problem here), but I also ran CSI:FingerID and Canopus. This all in steps and over the last weeks.

now I write the summaries and it only gives me a list of 437 features for formula identification, while if I look inside the folders of features that are not in the list, they do have formula candidates.

Canupus output is completely empty.

Is this a bug or am I missing something why the information is not ending up in the summary files?

**Comment by mfleisch** [comment]
Sorry for the late response. Can you provide the project so that I can have a look what is going wrong here.

I am closing this for now since it is likely that this is not relevant anymore due to the late response.

If it is still relevant please reopen.
