### ISSUE TITLE
how to import raw data into Sirius

### ISSUE THREAD

**Issue by yifanhh** [sirius-ms/sirius#133]
Hi, all. I hope to know how to import raw data (or spectrum) into Sirius app. The MS data was acquired in agilent Q-TOF

**Comment by naganarendrareddy2024** [comment]
Hi everyone,

I am trying to do CANOPUS compund class predictions using MS-DIAL output, I am using the GNPS output mgf file in SIRIUS, but when I look at the "CANOPUS formula summary" foutput file from SIRIUS , i do not see the correct alignment IDs corresponding to the MS-DIAL output? Please suggest solutions.
