### ISSUE TITLE
No web service connection

### ISSUE THREAD

**Issue by duanlaoyao** [sirius-ms/sirius#142]
The tools developed by your team are of great help to metabolomics research. However, when using the canopus module, it shows that the network cannot be connected. How should this situation be handled?
![image](https://github.com/boecker-lab/sirius/assets/146741565/3c894f84-15f1-4f3e-a934-9861bb046543)
![image](https://github.com/boecker-lab/sirius/assets/146741565/1619aed2-531f-40e2-99c4-d46e4124c1aa)

**Comment by xdkong** [comment]
Is your issue resolved now?

**Comment by mfleisch** [comment]
This was an temporary server outage -> closed
