### ISSUE TITLE
Question of `molecularFormula` and `precursorFormula`

### ISSUE THREAD

**Issue by JosieHong** [sirius-ms/sirius#150]
Good day, I recently tried using SIRIUS 5.8.6 for Linux (64-bit), and I noticed that for all the results, the `molecularFormula` and `precursorFormula` values were identical. Is this the expected behavior? To provide more context, I am attaching one of the input MGF files I used: 

```
BEGIN IONS
TITLE=tmp
PEPMASS=165.07907500000002
CHARGE=1+
ION=[M+H]+
MS_LEVEL=2
77.03900 3.8
91.05600 12.1
103.05300 9.1
119.04940 6.5
121.06410 41.8
123.04140 8.3
131.04770 11.1
137.06180 56.1
149.06080 47.1
166.08690 100.0
END IONS
```

Thanks!

**Comment by mfleisch** [comment]
I think there is a bug in the summary writer of SIRIUS 5 that will likely not be fixed anymore. 
However the summaries in SIRIUS 6 should not be affected. So upgrading should solve the issue. 

If you still have problems with SIRIUS 6 please reopen the issue.
