### ISSUE TITLE
How to invoke sirius.exe file from other application using the command line

### ISSUE THREAD

**Issue by Surajpatil07** [sirius-ms/sirius#153]
I am working on an C# WPF application and I want to start running the sirius.exe with the help of command line. I have .mgf file as input. 
I will just give an example of how I am using another applications .exe file and want to do the same with sirius.exe.
Process anotherapp = new Process();
            anotherapp.StartInfo.FileName = "exefilelocation";
            anotherapp.StartInfo.Arguments = "anyarguments";
            anotherapp.Start();
            anotherapp.Close();

I am not sure were to add the location of the mgf file as an input when using sirius.exe

**Comment by mfleisch** [comment]
Please have a look into our freshly updated documentation to get some infotmation abput how to use the command line tool:
https://v6.docs.sirius-ms.io/cli/

In case you have further question or want to further discuss the topic feel free to join our new `sirius-ms` gitter community:  https://matrix.to/#/#sirius-ms:gitter.im
