### ISSUE TITLE
When & How to merge multiple eV into one .mgf file?

### ISSUE THREAD

**Issue by DaWeMoYe** [sirius-ms/sirius#154]
When & How to merge multiple eV into one .mgf file?

For me, After running in MZmine3, I'v got 10eV.mgf, 20eV.mgf, 40eV.mgf. 
But in SIRIUS which need a merged.mgf, and I just do not know how to merge.
And I tried just put these 3 mgf files into SIRIUS at the same time, but I do not sure if it was right.
Please help me, Thanks very mach!

**Comment by kaibioinfo** [comment]
Put them into the same file and give them the same FEATURE_ID. They should be merged then. MZMine does also have a "export SIRIUS mgf" tool that should format the files properly.

**Comment by mfleisch** [comment]
Closed, Question has been answered.
