### ISSUE TITLE
SIRIUS 6: Input more than >1000 .ms files

### ISSUE THREAD

**Issue by fumiomatsuda** [sirius-ms/sirius#160]
Dear SIRIUS development team.

Thanks again for developing SIRIUS!

In the GUI version of SIRIUS 6.0.0, "Import" and drag and drop of >1000 .ms files and a folder including >1000 files did not work (nothing happened).
It was possible in SIRIUS 5 and the CLI version of SIRIUS 6

Thanks!

Fumio

**Comment by kaibioinfo** [comment]
I assume there is some internal limit of how much files you can transfer via http at once which is hit here. We will fix that with next patch.
