### ISSUE TITLE
sirius 6 in Linux

### ISSUE THREAD

**Issue by shitianhuo** [sirius-ms/sirius#161]
I'm using sirius in linux, but my commands don't seem to be correct and there is no output summary file, I don't quite understand how to use it, can you give me a clear example, for example, my parameters in the GUI are like this, how do I set it up in linux?

sirius --input TEST.mgf --output output.sirius \
formula -p orbitrap -c 5  --ppm-max 5 --ppm-max-ms2 5 -i [M-H]- \
zodiac fingerprint canopus structure --database ALL denovo-structures  \
write-summaries --output  summary-files-dir

![image](https://github.com/sirius-ms/sirius/assets/125648454/dd1e4c1e-ac1b-4a3e-8056-5bbf47cad69a)
config spectra-search --FormulaSearchSettings.applyFormulaConstraintsToBottomUp=false --IsotopeSettings.filter=true --UseHeuristic.useOnlyHeuristicAboveMz=650 --FormulaSearchDB=, --Timeout.secondsPerTree=0 --FormulaSettings.enforced=H,C,N,O,P --Timeout.secondsPerInstance=0 --AlgorithmProfile=orbitrap --SpectralMatchingMassDeviation.allowedPeakDeviation=5.0ppm --AdductSettings.enforced=, --AdductSettings.prioritizeInputFileAdducts=true --UseHeuristic.useHeuristicAboveMz=300 --IsotopeMs2Settings=IGNORE --MS2MassDeviation.allowedMassDeviation=5.0ppm --SpectralMatchingMassDeviation.allowedPrecursorDeviation=5.0ppm --FormulaSearchSettings.performDeNovoBelowMz=400.0 --FormulaSearchSettings.applyFormulaConstraintsToDatabaseCandidates=false --EnforceElGordoFormula=true --NumberOfCandidatesPerIonization=1 --FormulaSettings.detectable=B,S,Cl,Se,Br --NumberOfCandidates=10 --AdductSettings.fallback=[[M-H]-] --FormulaSearchSettings.performBottomUpAboveMz=0 --ZodiacNumberOfConsideredCandidatesAt300Mz=10 --ZodiacRunInTwoSteps=true --ZodiacEdgeFilterThresholds.minLocalConnections=10 --ZodiacEdgeFilterThresholds.thresholdFilter=0.95 --ZodiacNumberOfConsideredCandidatesAt800Mz=50 --FormulaResultThreshold=true --ExpansiveSearchConfidenceMode.confidenceScoreSimilarityMode=APPROXIMATE --StructureSearchDB=METACYC,BloodExposome,CHEBI,COCONUT,FooDB,GNPS,HMDB,HSDB,KEGG,KNAPSACK,LOTUS,LIPIDMAPS,MACONDA,MESH,MiMeDB,NORMAN,PLANTCYC,TeroMol,YMDB --RecomputeResults=false formulas zodiac fingerprints classes structures denovo-structures

**Comment by mfleisch** [comment]
Can you please try again with SIRIUS 6.0.5 or later. A if it does still not work provide the console output your are getting when running the command?
