### ISSUE TITLE
Sirius 6 How do I know which Sirius internal ID corresponds to in the original ID in the input file?

### ISSUE THREAD

**Issue by DY970313** [sirius-ms/sirius#165]
Hello,
I did a compound annotation task of mgf data using Sirius 6 with GUI. Everything was perfect until the results were exported.
But when I exported the summary file, I found that
1）.tsv files had no original ID, only Sirius ID.
For example: a feature in .mgf had an original ID of `Unkown(0.09_396.0852m/z)` and a Sirius ID of `589266962313865030`, as shown below (in Sirius 6 GUI).
![image](https://github.com/sirius-ms/sirius/assets/110038753/a6bc491f-d05e-4d04-8fd3-dab7044d2823)
In all exported .tsv, there iwas no original ID. The exported IDs are as follows. .mgf and table derived from "FBMN  export" were also all Sirius ID.
```
formulaId	alignedFeatureId	mappingFeatureId
589267320599701454	589266962313865030	589266962313865030
```
2）No report.mztab file was exported

So, I have no way of knowing which Sirius internal ID corresponds to in the original ID in the .mgf file, except in the GUI. However, I have thousands of features and cannot manually check them one by one on the GUI.
Is there any other way to get it?

Thank you very much！

**Comment by DY970313** [comment]
As a supplement, I tried to replace the original ID by the simpler value, e.g. C1, C2 and C3. But the problem still existed.

**Comment by MartinHoffmannJena** [comment]
Hey, 

are you able to share an example mgf containing compounds with an "original ID"?

**Comment by DY970313** [comment]
> Hey,
> 
> are you able to share an example mgf containing compounds with an "original ID"?

Of course, here's two features in my .mgf. The raw data (waters, `.raw`) was  processed by Progenesis QI software and the fragments were exported as `.msp` file, and then converted to `.mgf` by MSP2MGF. Also, I tried to run the same .mgf on **Sirius 5.7.8** and this issue did not occur. 


```
BEGIN IONS
TITLE=Unknown (13.13_277.4333m/z)
CHARGE=1-
PEPMASS=277.4333
#Comment=13.13_277.4333m/z
99.9246 19.5822
233.2265 14.4502
259.2059 5.8892
265.1469 3.9191
269.2457 4.7878
275.2006 11.4235
277.2162 7155.4311
277.3005 48.1023
277.3527 102.2289
END IONS

BEGIN IONS
TITLE=Unknown (13.13_293.1783m/z)
CHARGE=1-
PEPMASS=293.1783
#Comment=13.13_293.1783m/z
99.9246 19.5822
233.2265 14.4502
259.2059 5.8892
265.1469 3.9191
269.2457 4.7878
275.2006 11.4235
277.2162 7155.4311
277.3005 48.1023
277.3527 102.2289
END IONS
```

**Comment by MartinHoffmannJena** [comment]
Hi,

The correct .mgf field for that is FEATURE_ID, not TITLE. The .mgf format is not really standardized, so everybody kind of uses different fields for different purposes. We use the TITLE field strictly as a name and grouping parameter, and the FEATURE_ID for the mapping.

For now, you could replace all your "TITLE" occurences with "FEATURE_ID", I'll check if TITLE and NAME are fields that we want to use as backup feature ids, if they are not defined

**Comment by DY970313** [comment]
> Hi,
> 
> The correct .mgf field for that is FEATURE_ID, not TITLE. The .mgf format is not really standardized, so everybody kind of uses different fields for different purposes. We use the TITLE field strictly as a name and grouping parameter, and the FEATURE_ID for the mapping.
> 
> For now, you could replace all your "TITLE" occurences with "FEATURE_ID", I'll check if TITLE and NAME are fields that we want to use as backup feature ids, if they are not defined

Thank you very much indeed!!!! My problem was solved perfectly!
