### ISSUE TITLE
Stuck at 100% when running on all data

### ISSUE THREAD

**Issue by HarryHung417** [sirius-ms/sirius#166]
![Screenshot 2024-06-17 010647](https://github.com/sirius-ms/sirius/assets/173009525/b013ca1c-e929-48d0-bd7a-8f4853120ae0)
I was running SIRIUS and CANOPUS on my ms/ms data for class prediction. The software stopped running at 100% of the main task, and at 35% for some of the 'fingerprint' steps. The last sentence in the log of the paused procedures says 'Invalidate existing Results and Recompute'. I am using SIRIUS 6.0.0 and is there a solution to this besides deleting the steps that are stuck?
![Screenshot 2024-06-17 011243](https://github.com/sirius-ms/sirius/assets/173009525/3af478d0-86a1-4398-9436-d872d951e165)

**Comment by typewritermonkey** [comment]
How long did you wait for your job? It looks like the Zodiac step takes the longest. I'll leave mine running today and check it again tonight. It should be able to run 4000 compounds without running out of javaheapspace I hope

![image](https://github.com/sirius-ms/sirius/assets/124550424/f12d9ce0-9ee9-428c-b180-729563b9f094)

**Comment by kaibioinfo** [comment]
ZODIAC needs a lot of memory actually. We have to implement a low-memory solution for that... :/
It computes pairwise similarities between all compounds (so in your case 4000 x 4000) and build up a huge graph. In molecular networks like GNPS this graph is shrinked down a lot to make visualisation easier. We keep the large graph - so it gets quite memory hungry.
If it's not doing anything for hours it might indeed run into infinite garbage collection :/

Maybe run ZODIAC only on a subset of good and decent features?

**Comment by typewritermonkey** [comment]
Is it still worth running Zodiac on 142 features? 

![image](https://github.com/sirius-ms/sirius/assets/124550424/743bbb45-3deb-422e-81bc-7d14ade64c7d)

**Comment by HarryHung417** [comment]
Thank you for the suggestions. I tried to remove ZODIAC and re-run the program. My only solution now is to go down a patch to SIRIUS 5.8 and it is working fine. I may try 6.0 again later

**Comment by Do-rossi** [comment]
Hi, 

I also have an issue that looks like that. It stopped around 80% when i run my data using Sirius, Canopus and Database search. I didn’t turn Zodiac on and I tried several times to cancel all and then compute using only Sirius but it doesn’t look better. My log also says “Invalidate existing Results and Recompute” and then start computation that never ends.

août 27, 2024 10:55:07 AM de.unijena.bioinf.jjobs.JJob lambda$logInfo$9
INFOS: <208>[BackgroundRunJob-208] Invalidate existing Results and Recompute!
août 27, 2024 10:55:07 AM de.unijena.bioinf.jjobs.JJob lambda$logInfo$9
INFOS: <289535>[FingerblastSubToolJob-289535 | 3215 (616176135210000831)] Invalidate existing Results and Recompute!
août 27, 2024 10:55:07 AM de.unijena.bioinf.jjobs.JJob lambda$logInfo$9
INFOS: <208>[BackgroundRunJob-208] Start computation...
août 27, 2024 10:55:07 AM de.unijena.bioinf.jjobs.JJob lambda$logInfo$9
INFOS: <289535>[FingerblastSubToolJob-289535 | 3215 (616176135210000831)] Start computation..

**Comment by mfleisch** [comment]
Should be fixed with latest updates. Please open a new issue if you still have similar problems.
