### ISSUE TITLE
High standards filter?

### ISSUE THREAD

**Issue by typewritermonkey** [sirius-ms/sirius#167]
Does the filter have really high standards or is most of my data just junk? I'm down from 22,000 features to 142 of 'good' or 'decent' quality

![sirius high standards](https://github.com/sirius-ms/sirius/assets/124550424/d4ff7f36-b2a4-4185-a5f5-24d1d3e03e9e)

Also if we do the FBMN export what option should we choose on the GNPS FBMN page that asks what the source of your feature quantification table was? Sirius isn't on the dropdown menu. Or do we need to process in MZmine first to make an MGF, then process in Sirius and export to FBMN from there? 
![sirius fbmn fail](https://github.com/sirius-ms/sirius/assets/124550424/b2015659-c688-4c8e-8e39-b8add29aae2e)

**Comment by typewritermonkey** [comment]
I think I figured out what the issue with the filter was. Almost all of my features are listed as [M+?] adducts, which I assume means that Sirius couldn't tell what the adduct type was, so they were getting filtered out. I get higher adduct annotation rates with MS-DIAL though I don't really know how accurate they are. Usually when I make FBMN IIMN networks with GNPS after MZmine it lists most of the nodes as feature nodes rather than ion identity nodes, which I think means it doesn't know the adduct type of most of my features either. Hard to predict the formula when you can't even be sure what the exact mass of the precursor was. I did SPE to try to reduce the salts before LCMS and I thought that plus the formic acid would mean most adducts would be the simple [M+H]+ type but I'm not sure what the exact percentage would be. Maybe it would be worth just telling the software to assume everything is an [M+H]+ even if means its sometimes wrong idk.

**Comment by kaibioinfo** [comment]
[M+?]+ means the adduct is not absolutely clear. It might be even an adduct detected, but if this assignment has low probability it's better to also consider alternative explanations.
In the end the adduct can still figured out in the structure annotation step, so I would not fix them too early.

If you want to enforce [M+H]+ whenever no adduct is known you can select [M+H]+ as 'fallback' adduct.

**Comment by typewritermonkey** [comment]
Ah makes sense thanks

**Comment by typewritermonkey** [comment]
I just tried FBMN on GNPS2 with a Sirius export but it failed there as well

![image](https://github.com/sirius-ms/sirius/assets/124550424/1809dc86-a54a-45ca-a186-3329e39c32b3)

**Comment by mfleisch** [comment]
Hey, we also had issues running fbmn on GNPS recently. We are investigating this right now.

**Comment by typewritermonkey** [comment]
I think Ming is working on it as well
