### ISSUE TITLE
SIRIUS Job Failed (first time user)

### ISSUE THREAD

**Issue by lelmasri** [sirius-ms/sirius#168]
Hi,
I'd appreciate any help. I've tried to run a few separate jobs but they keep failing. Any help is much appreciated!

Here is the log where one of the failures occurred:

Jun 17, 2024 3:25:42 PM de.unijena.bioinf.jjobs.JJob lambda$logError$1
SEVERE: <800>[SiriusSubToolJob-800 | 40 (590668103630952630)] ToolChain Job failed due to: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3

How do I change the bounds so this doesn't fail when using the GUI?

Thanks in advance!

**Comment by kaibioinfo** [comment]
Hi, this could be a bug I'm already fixing. Currently the dev team is quite busy with ASMS and metabolomics conference, but there will be a patch with bugfixes soon.

**Comment by mfleisch** [comment]
Likely fixed, but to less information to be sure. Please reopen if problem persists,
