### ISSUE TITLE
Interminable job with Sirius 6 (Problem with the server respons)

### ISSUE THREAD

**Issue by TOTOZAFY** [sirius-ms/sirius#171]
Hi Sirius developper, 

I had some problem with sirius 6, i started a job with arround 3000 features, so i compute all of them and the job was never finished it's one week now and i had the same problem of server respons, do you have any solution to fix this problem.

AVERTISSEMENT: Request to Server failed! Try again in 120.0s | Exception: de.unijena.bioinf.rest.SiriusHttpException | Cause: Http Request Failed in client `JOB_SUBMITTER`. Cause: `HttpErrorResponseException` | Message: `Error when querying REST service. Bad HTTP Response Code: 500 | HTTP-Message:  | HTTP-Request: POST: https://csi.bright-giant.com/v3.0/api/jobs/0l-fPDUf2g1An8v2jJ7HBPboMmeqo2XhAcWUEtiwInopAbR7WsPnisvsnu-7GS-1`

Thank you

**Comment by mfleisch** [comment]
Hey, this should be fixed in 6.0.4. 
Feel free to re open the issue if the problem persists with the new version.
