### ISSUE TITLE
How do I increase the number of decimal places shown for the mass?

### ISSUE THREAD

**Issue by typewritermonkey** [sirius-ms/sirius#173]
Hi 

When I'm trying to find a particular m/z I often need the mass to the 3rd or 4th decimal but Sirius only seems to show to the second decimal. Is there an option to increase this?

**Comment by marcus-ludwig** [comment]
Hi,

Yes, SIRIUS only displays the first 2 decimals. However, you can search - in the text box or the detailed filter dialog - for the exact m/z. The summary .tsv-files contains also the exact m/z.
