### ISSUE TITLE
Feature Request: Exporting CSI:FingerID Fingerprint values

### ISSUE THREAD

**Issue by AsetMuratuly** [sirius-ms/sirius#175]
Dear Sirius team!

Thank you very much for maintaining and developing this tool.

In previous versions of Sirius, it was possible to export the probabilities of fingerprints calculated by CSI:FingerID. However, in version 6.0.0, I couldn't find an option to export these probabilities, either as part of the project in the workspace, nor I could find a dedicated feature for this.

Could you please provide guidance on how to export fingerprint probabilities in the current version? If this functionality is not currently available, would it be possible to consider adding this feature in future updates?

Cheers

**Comment by marcus-ludwig** [comment]
Hi,

Yes, with SIRIUS 6 we changed the project space to using a database.  Hence the old file-base retrieval is not available anymore.

You can still retrieve the fingerprints via the new API: https://v6.docs.sirius-ms.io/quick-start/#background-service---generic-sirius-api

We are working on providing client SDKs for different scripting languages: https://github.com/sirius-ms/sirius-client-openAPI
The  Python SDK will be the first to be available. Once available, you can install it via pip as explained in the GitHub repo. And it will also be available via conda: https://anaconda.org/conda-forge/py-sirius-ms

Best,
Marcus
