### ISSUE TITLE
Job Stuck on Fingerprint/CANOPUS Step

### ISSUE THREAD

**Issue by zglong1** [sirius-ms/sirius#176]
I'm trying to process a .mgf file from MZMine, like I've done many times before. There's 431 features, far from the most I've processed before, and I'm running into an issue where the job stalls at 94% (when running this step individually rather than the full process at once, which also didn't work). The log just repeats for hours on end with no progress, repeating the following: 
..."
ul 17, 2024 10:47:43 AM de.unijena.bioinf.jjobs.JJob lambda$logDebug$13
FINE: <19329>[CheckJob-19329] Running cleanup
Jul 17, 2024 10:48:04 AM de.unijena.bioinf.jjobs.JJob lambda$logDebug$13
FINE: <19332>[CheckJob-19332] Running post processing
Jul 17, 2024 10:48:04 AM de.unijena.bioinf.jjobs.JJob lambda$logDebug$13
FINE: <19332>[CheckJob-19332] Running cleanup
Jul 17, 2024 10:48:04 AM de.unijena.bioinf.jjobs.JJob lambda$logDebug$13
FINE: <19331>[CheckJob-19331] Running post processing
Jul 17, 2024 10:48:04 AM de.unijena.bioinf.jjobs.JJob lambda$logDebug$13
FINE: <19331>[CheckJob-19331] Running cleanup
Jul 17, 2024 10:48:24 AM de.unijena.bioinf.jjobs.JJob lambda$logDebug$13
FINE: <19334>[CheckJob-19334] Running post processing
Jul 17, 2024 10:48:24 AM de.unijena.bioinf.jjobs.JJob lambda$logDebug$13
FINE: <19334>[CheckJob-19334] Running cleanup
Jul 17, 2024 10:48:24 AM de.unijena.bioinf.jjobs.JJob lambda$logDebug$13
FINE: <19333>[CheckJob-19333] Running post processing
Jul 17, 2024 10:48:25 AM de.unijena.bioinf.jjobs.JJob lambda$logDebug$13
FINE: <19333>[CheckJob-19333] Running cleanup
"...

I've attached the .mgf file in question.

I can't tell if it's a resource issue (I'm not even close to 40% RAM usage and at <10% CPU usage), or a legitimate issue, but I figured I'd post. I think I'll try processing in an earlier version of SIRIUS to see.

[MZMine SIRIUS Export.zip](https://github.com/user-attachments/files/16272829/MZMine.SIRIUS.Export.zip)

**Comment by zglong1** [comment]
This is using SIRIUS 6.0.0.

**Comment by NNavrot** [comment]
Hi,
similar issue here. We have had this problem for a couple of days now.

**Comment by zglong1** [comment]
Using 6.0.1 it still seems to stall, but this time at 95% on the structure database search/ID step. The first bit went quickly, but once at 95% it sat overnight with no progress.

**Comment by savannahanez** [comment]
I am having the same problem! I started the job 4 days ago and it is still running with the same messages. I am using 6.0.0, please let me know how it went with a 5.x.x version!

**Comment by ZarluisMijangoR** [comment]
Hello y'all,

I haven't started my run just yet but I will soon. Looking at your job comments and issues it feels like I could potentially head up that way too. I will be using an output file from MZmine (sirius.mgf) with 15K features. I use SIRIUS 6.0.1. So I am also looking forward to a potential solution for this :)

I also wonder if there is a way to optimise parameters so the run goes quicker and smooth, specially when one has a file with lots of features (I haven't seen anything about this, maybe I have missed it?).

Kind regards,
Zarluis

**Comment by typewritermonkey** [comment]
The only way I can complete big jobs from MZmine is by turning off Zodiac. Otherwise it just eats all of my RAM (64GB), gets stuck and crashes. 431 features isn't that many though it should be able to handle that I would have thought.  I wish MZMine had its own peak quality filter because 10K+ features is a bit ridiculous to work with

**Comment by typewritermonkey** [comment]
> Hello y'all,
> 
> I haven't started my run just yet but I will soon. Looking at your job comments and issues it feels like I could potentially head up that way too. I will be using an output file from MZmine (sirius.mgf) with 15K features. I use SIRIUS 6.0.1. So I am also looking forward to a potential solution for this :)
> 
> I also wonder if there is a way to optimise parameters so the run goes quicker and smooth, specially when one has a file with lots of features (I haven't seen anything about this, maybe I have missed it?).
> 
> Kind regards, Zarluis

What happened with your job?

**Comment by mfleisch** [comment]
Hey,
all job scheduling issues in SIRIUS 6 we were aware of have been addressed until v6.0.4.

I am closing this issue. please reopen or create an new issue if similar problems still exist.

**Comment by mfleisch** [comment]
> The only way I can complete big jobs from MZmine is by turning off Zodiac. Otherwise it just eats all of my RAM (64GB), gets stuck and crashes. 431 features isn't that many though it should be able to handle that I would have thought. I wish MZMine had its own peak quality filter because 10K+ features is a bit ridiculous to work with

You could give SIRIUS internal preprocessing a shot. If the preprocessing has been performed by SIRIUS itself you can now filter features by many different quality measures.
