### ISSUE TITLE
Issue with Connection to Sirius Webservice

### ISSUE THREAD

**Issue by Azlaikha02** [sirius-ms/sirius#184]
I have downloaded SIRIUS 5.5.1 and logged into my account, however, I have a problem regarding the connection to the login server and the Sirius web service that I still don't know how to solve.  The workers availability also shows a problem.

![SIRIUS connection issue](https://github.com/user-attachments/assets/0db0b585-1c17-4f10-b2a7-1f5e1a1768cc)

**Comment by mfleisch** [comment]
Hey, 
SIRIUS 5.5.1 is very old and no longer maintained. 

If you want to use SIRIUS 5 please upgrade to:
https://github.com/sirius-ms/sirius/releases/tag/v5.8.6

If you Want to use SIRIUS 6 please download the latest version
https://github.com/sirius-ms/sirius/releases/latest

I close this issue, please feel free to reopen it in case you still have connection problems after upgrading.

**Comment by Azlaikha02** [comment]
Thank you so much, it worked
