### ISSUE TITLE
Custom Database 

### ISSUE THREAD

**Issue by Azlaikha02** [sirius-ms/sirius#190]
Hi there 
I'm currently on SIRIUS v 6.0.2, and Windows 11, I want to create a custom database based on an "in-house database" in Microsoft Excel. I tried to save the database as CSV (comma delimited), however, when I inserted the database it showed empty. Do you know if this is normal? because I would like to apply my database when computing the data. 
![image](https://github.com/user-attachments/assets/15b65618-9319-41aa-9432-d3d46c95538c)

**Comment by mfleisch** [comment]
Hey,
Sirius custom database import expects either .tab (tab separated files) or various spectral library formats like such as NIST `.msp` as Input.

See the Link below for an example tab file and further information.
https://boecker-lab.github.io/docs.sirius.github.io/cli-standalone/#custom-database-tool
