### ISSUE TITLE
Account invalid signup

### ISSUE THREAD

**Issue by JyotiAgg5** [sirius-ms/sirius#194]
Hello SIRIUS team,
I cannot create an account on SIRIUS using my educational ID: '***'. The signup page shows 'Invalid signup'.

![SIRIUS signup issue](https://github.com/user-attachments/assets/6113b55a-4b2f-45f2-992e-2ce5a52477ee)

Please help me get an account for the educational purpose.

Thank you.

**Comment by mfleisch** [comment]
Hey,
your account already exists in our system. In case you forgot your password 
please use the password reset features in the [user portal ](https://portal.bright-giant.com/) to create a new one.  

In case you are not receiving the emails (we noticed that a few universities are "blocking/filtering" our systems emails) please reopen the issue and let us know.
