### ISSUE TITLE
Issue while importing mgf files

### ISSUE THREAD

**Issue by GuilhemZerbini** [sirius-ms/sirius#195]
I have been using Sirius 5.8.6 since February for compound annotation on HRMS data with positive ionization and did not have any particular issue with the software. However, I need to annotate compound found in negative ionisation HRMS data and i encountered an issue while importing the mgf file.

I did the same processing on the negative data using MZmine 3 before exporting to an mgf file and I have about 1500 features from that according to MZmine. After exporting the data to a mgf format and importing it to Sirius, I only have 25 features, none of them having a m/z over 165 Da. The sample used is a mix of analyticals standards so i know what i am supposed to find and I know that most my compound have a m/z higher than 165. A quick check on the feature table from MZmine shows that the compounds I am looking for are in check in the feature list.

I checked all filter to be sure the problem is not due to that, the m/z filter and RT filter are set to "0-Infinite", the confidence filter is set to "0-1", low, medium and high Peak shape quality are selected, the "keep all compounds" is also selected (see picture).

![Issue Sirius](https://github.com/user-attachments/assets/1d36b0c2-21cf-444a-ad32-8e91e54deb47)

From what I know, it is not possible to adjust parameters while importing mgf file on Sirius. Do you know if there is something I could do to have all the features I need?

Thank you in advance,

Best regards,

Guilhem Zerbini

**Comment by mfleisch** [comment]
Hey Guilhem, 
can you please check if the compounds your found in the feature list are also part of the mgf you exported?
do the features you are expecting to be there have ms/ms data?

**Comment by GuilhemZerbini** [comment]
Hello,

Thank you for your answer.
I checked and yes, the compounds i found in the feature list are part of the mgf file i imported.
I also checked if the feature I expect have MS/MS data and yes, they have. On the 20 or so compounds I expect, i can find 1 or 2 in Sirius (from the 25 features shown by Sirius) but i can't find the other. However, the features with MS and MS/MS data appears on the mgf file i have from a MZmine exportation wich worked in positive ionization.

**Comment by MartinHoffmannJena** [comment]
Hi Guilhem,

Is it possible for you to share the .mgf file so that we can take a look?

**Comment by GuilhemZerbini** [comment]
Hello Martin,

Sure, here is the mgf file : [https://we.tl/t-qqIQid1Org] (url)

Thank you in advance

**Comment by MartinHoffmannJena** [comment]
Hi Guilhelm,

I looked into the .mgf and there are only 27 features in there, all which SIRIUS correctly imports (you can check that by counting the number of unique FEATURE_IDs). So the issue seems to be on the MZmine exporting side not exporting the rest of your features, which we cannot assist with here. 

Please open an issue on the MZmine github page as this is not an issue with SIRIUS.

**Comment by GuilhemZerbini** [comment]
Hello Martin, thank you for your answer, I will get in touch with MZmine then.

Thank you for your help
