### ISSUE TITLE
Email not received.

### ISSUE THREAD

**Issue by JyotiAgg5** [sirius-ms/sirius#197]
Hello Dr. Fleischauer,

Thank you for the response to the invalid account signup issue.

I tried resetting the password. However, I didn't receive any email. 

I have contacted the IT department of our educational webmail (as you suggested about blocking/filtering emails by the system).

To track and figure out, the department needs to know the email address used by the software to send the emails.
This will help figure out more easily and quickly.
Please help me with the same.

Thank you in anticipation.

**Comment by mfleisch** [comment]
I followed up on https://matrix.to/#/#sirius-ms:gitter.im which is the better place to exchange pms.
