### ISSUE TITLE
The fragmentation tree API tool does not return valid source or target node IDs.

### ISSUE THREAD

**Issue by adriaolomi** [sirius-ms/sirius#199]
Hi,

I have been able to export the fragmentation tree of a compound using the API. However, when I check the response JSON I realize that almost all of the fragments-id are zero (both source and target nodes). It would be interesting for me to have those indices in order to build the fragmentation graph in my workflow.

I attach the JSON in the following.
[test.json](https://github.com/user-attachments/files/16944960/test.json)

**Comment by MartinHoffmannJena** [comment]
Hi,

Thank you for your report, we are looking into it now. I'll let you know once we have a fix
