### ISSUE TITLE
no connection to SiRiuS

### ISSUE THREAD

**Issue by FARKH69** [sirius-ms/sirius#215]
*I have been unable to log in to SiRiuS, even with my academic email. Could you please assist me in resolving this issue?

**Comment by MartinHoffmannJena** [comment]
Hi,

Could you please provide a screenshot of the "webservice" dialogue in the GUI and a copy of the SIRIUS log?

**Comment by FARKH69** [comment]
Sure, here it is.
this is fine now,
Many many thanks,
FK

[image: image.png]


Le lun. 4 nov. 2024 à 13:36, Martin Hoffmann ***@***.***> a
écrit :
