### ISSUE TITLE
[BUG] - v6.0.7 - Can't access Summaries or FBMN export 

### ISSUE THREAD

**Issue by gfschnei** [sirius-ms/sirius#220]
**Bug description**
>This was my first instance using v6.0.7 after updating. After finishing all computation processes on an .mgf file imported from MzMine3, QToF data in positive mode, neither the Summaries or FBMN Export buttons work. As in, in the GUI, the buttons on the banner menu are grayed-out. 
![sirius6 0 7issue](https://github.com/user-attachments/assets/a9fb79e1-3b0a-4771-97e3-492cc22f7373)

**Expected behavior**
> Normally, in previous versions of Sirius, I have been able to export summary and FBMN files by using the buttons in the banner menu.

**Steps To Reproduce**
1. Import Sirius-specific .mgf from MZMine3 output
2. Run all available computations
3. Wait for computation jobs to complete

**System Info (please complete the following information):**
 - **OS and Version:** Windows 10 Pro 22H2 64 bit
 - **SIRIUS Version** 6.0.7
 - **Hardware** Intel Core i7-8700 CPU @ 3.20GHz, 32GB RAM

**Comment by MartinHoffmannJena** [comment]
Hi,

are you able to share the .sirius project space this happened with?

**Comment by MartinHoffmannJena** [comment]
Thank you, the buttons are there for me when I open the project and work as expected.

Did you try to restart SIRIUS and re-open the project?
