### ISSUE TITLE
Export of Tanimoto similarity to structure_candidates.tsv

### ISSUE THREAD

**Issue by JethroHemmann** [sirius-ms/sirius#95]
Hi, 

I was wondering if there is a way to access the Tanimoto similarity score (xx%), which is shown below the structures in SIRIUS, after exporting the project/summaries?

In the `structure_candidates.tsv` I could not find the information.

**Comment by JethroHemmann** [comment]
Thanks, that´s good to know!

**Comment by mfleisch** [comment]
Just update this after SIRIUS 6 release: The tanimoto similarity is accessible via the new API, as part of the structure candidates. See https://v6.docs.sirius-ms.io/quick-start/#API for details.
